[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "LeagueSpartan-VariableFont_wght"
url = "app/static/LeagueSpartan-VariableFont_wght.ttf"
style = "normal" 
[theme]
base = "light"
font = "LeagueSpartan-VariableFont_wght"
primaryColor="#995ec5"
